window.siteWorks = {
  caffeina: [
    {
      title: "i ft.初音ミク",
      description: "Caffeina 1作目",
      role: "楽曲制作, 映像編集",
      date: "2022-01-12",
      type: "Music",
      cover: "./Caffeina_I_thumb.jpg",
      url: "https://www.nicovideo.jp/watch/sm39886223",
    },
    {
      title: "0 gravity ft.初音ミク",
      description: "Caffeina 2作目",
      role: "作詞曲・編曲",
      date: "2022-02-18",
      type: "Music",
      cover: "./Caffeina_0gravity_thumb.jpg",
      url: "https://www.nicovideo.jp/watch/sm40040030",
    },
    {
      title: "海鳴り ft.初音ミク",
      description: "Caffeina 3作目",
      role: "作詞曲・編曲",
      date: "2022-08-31",
      type: "Music",
      cover: "./Caffeina_Uminari_thumb.jpg",
      url: "https://www.nicovideo.jp/watch/sm41011733",
    },
    {
      title: "春靄へ。 ft.初音ミク",
      description: "Caffeina 4作目",
      role: "楽曲共作, 映像編集",
      date: "2023-05-01",
      type: "Music",
      cover: "./Caffeina_Harumoya_thumb.jpg",
      url: "https://www.nicovideo.jp/watch/sm42158269",
    },
    {
      title: "夏風邪 ft.初音ミク",
      description: "Caffeina 5作目",
      role: "共作詞編曲, 映像編集",
      date: "2023-08-04",
      type: "Music",
      cover: "./Caffeina_Natsukaze_thumb.jpg",
      url: "https://www.nicovideo.jp/watch/sm42573094",
    },
    {
      title: "煤煙 ft.知声",
      description: "無色透名祭3 参加曲",
      role: "楽曲共作, 映像編集",
      date: "2025-11-21",
      type: "Music",
      cover: "./Caffeina_Baien_thumb.jpg",
      url: "https://www.nicovideo.jp/watch/so45520678",
    },
  ],
  peristeronica: {
    music: [
      {
        title: "LATEST WORK",
        description: "Peristeronicaの最新楽曲。",
        role: "Music",
        date: "2026-05-09",
        type: "Music",
        cover: "./Peristeronica_LatestWork.jpg",
        url: "https://www.youtube.com/watch?v=WfE4c6p-zO4",
      },
    ],
    other: [
      {
        title: "1day_DTM",
        description: "短い楽曲のまとめ。",
        role: "Music",
        date: "2026-05-09",
        type: "1day_DTM",
        cover: "./Peristeronica_icon.png",
        collection: [
          {
            title: "1day_DTM archive item",
            description: "短い楽曲をここに追加します。",
            role: "Music",
            date: "2026-05-09",
            cover: "./Peristeronica_LatestWork.jpg",
          },
        ],
      },
      {
        title: "Illust",
        description: "イラストのまとめ。",
        role: "Illustration",
        date: "2026-05-09",
        type: "Illust",
        cover: "./Peristeronica_icon.png",
        collection: [
          {
            title: "Illust archive item",
            description: "イラストをここに追加します。",
            role: "Illustration",
            date: "2026-05-09",
            cover: "./Peristeronica_icon.png",
          },
        ],
      },
      {
        title: "1day_Movie",
        description: "短い映像のまとめ。",
        role: "Movie",
        date: "2026-05-09",
        type: "1day_Movie",
        cover: "./Peristeronica_icon.png",
        collection: [
          {
            title: "1day_Movie archive item",
            description: "短い映像をここに追加します。",
            role: "Movie",
            date: "2026-05-09",
            cover: "./Peristeronica_LatestWork.jpg",
          },
        ],
      },
    ],
  },
};
