window.siteWorks = {
  caffeina: [
    {
      title: "i ft.初音ミク",
      description: "Caffeina 1作目",
      role: "楽曲制作, 映像編集",
      date: "2022-01-12",
      type: "Music",
      cover: "./Caffeina_I_thumb.jpg",
      url: "https://www.nicovideo.jp/watch/sm39886223",
    },
    {
      title: "0 gravity ft.初音ミク",
      description: "Caffeina 2作目",
      role: "作詞曲・編曲, 映像編集",
      date: "2022-02-18",
      type: "Music",
      cover: "./Caffeina_0gravity_thumb.jpg",
      url: "https://www.nicovideo.jp/watch/sm40040030",
    },
    {
      title: "海鳴り ft.初音ミク",
      description: "Caffeina 3作目",
      role: "作詞曲・編曲, 映像編集",
      date: "2022-08-31",
      type: "Music",
      cover: "./Caffeina_Uminari_thumb.jpg",
      url: "https://www.nicovideo.jp/watch/sm41011733",
    },
    {
      title: "春靄へ。 ft.初音ミク",
      description: "Caffeina 4作目",
      role: "楽曲共作, 映像編集",
      date: "2023-05-01",
      type: "Music",
      cover: "./Caffeina_Harumoya_thumb.jpg",
      url: "https://www.nicovideo.jp/watch/sm42158269",
    },
    {
      title: "夏風邪 ft.初音ミク",
      description: "ボカコレ2023夏 参加曲",
      role: "共作詞編曲, 映像編集",
      date: "2023-08-04",
      type: "Music",
      cover: "./Caffeina_Natsukaze_thumb.jpg",
      url: "https://www.nicovideo.jp/watch/sm42573094",
    },
    {
      title: "煤煙 ft.知声",
      description: "無色透名祭3 参加曲",
      role: "楽曲共作, 映像編集",
      date: "2025-11-21",
      type: "Music",
      cover: "./Caffeina_Baien_thumb.jpg",
      url: "https://www.nicovideo.jp/watch/so45520678",
    },
  ],
  peristeronica: {
    music: [
      {
        title: "煤煙 ft.知声",
        description: "無色透名祭3 参加曲",
        role: "楽曲共作",
        date: "2025-11-21",
        type: "Music",
        cover: "./Caffeina_Baien_thumb.jpg",
        url: "https://www.nicovideo.jp/watch/so45520678",
      },
      {
        title: "ラピッド ft.鏡音リン, 初音ミク",
        description: "ボカコレ2025夏 参加曲",
        role: "企画, 楽曲制作",
        date: "2025-08-23",
        type: "Music",
        cover: "./Peristeronica_Rapid_thumb.jpg",
        url: "https://www.nicovideo.jp/watch/sm45323373",
      },
      {
        title: "0 gravity ft.初音ミク",
        description: "Caffeina 2作目",
        role: "Mix, Master",
        date: "2022-02-18",
        type: "Music",
        cover: "./Caffeina_0gravity_thumb.jpg",
        url: "https://www.nicovideo.jp/watch/sm40040030",
      },
      {
        title: "海鳴り ft.初音ミク",
        description: "Caffeina 3作目",
        role: "Mix. Master",
        date: "2022-08-31",
        type: "Music",
        cover: "./Caffeina_Uminari_thumb.jpg",
        url: "https://www.nicovideo.jp/watch/sm41011733",
      },
      {
        title: "春靄へ。 ft.初音ミク",
        description: "Caffeina 4作目",
        role: "楽曲共作",
        date: "2023-05-01",
        type: "Music",
        cover: "./Caffeina_Harumoya_thumb.jpg",
        url: "https://www.nicovideo.jp/watch/sm42158269",
      },
      {
        title: "夏風邪 ft.初音ミク",
        description: "ボカコレ2023夏 参加曲",
        role: "楽曲共作",
        date: "2023-08-04",
        type: "Music",
        cover: "./Caffeina_Natsukaze_thumb.jpg",
        url: "https://www.nicovideo.jp/watch/sm42573094",
      },
      {
        title: "梅雨の終わりに ft.初音ミク",
        description: "デジクリ 2023前期MV企画 参加曲",
        role: "企画, 運営, 一次楽曲制作",
        date: "2023-11-03",
        type: "Music",
        aspect: "square",
        playback: { start: 500, end: 642 },
        cover: "./Peristeronica_Tsuyu_thumb.jpg",
        url: "https://youtu.be/9g332gWaVZY?t=500&si=eiB_aqg_e4crYNT8",
      },
      {
        title: "ネビュラリフレクション ft.初音ミク",
        description: "デジクリ 2023前期MV企画 参加曲",
        role: "企画, 運営, 二次楽曲制作",
        date: "2023-11-04",
        type: "Music",
        aspect: "square",
        playback: { start: 863, end: 967 },
        cover: "./Peristeronica_NebulaReflection_thumb.jpg",
        url: "https://youtu.be/9g332gWaVZY?t=863&si=72gA1lKuLSuotzxo",
      },
      {
        title: "地平線の見える場所 ft.裏命",
        description: "デジクリ 2023後期MV企画 参加曲",
        role: "企画, 運営, 一次楽曲制作",
        date: "2024-05-20",
        type: "Music",
        aspect: "square",
        playback: { start: 972, end: 1103 },
        cover: "./Peristeronica_Chiheisen_thumb.jpg",
        url: "https://youtu.be/qwLuP_dGzGM?t=972&si=UT7XA4kmw4a5g29Z",
      },
      {
        title: "Rainbow_Midnight ft.初音ミク",
        description: "デジクリ 2023後期MV企画 参加曲",
        role: "企画, 運営, 二次楽曲制作",
        date: "2024-05-21",
        type: "Music",
        aspect: "square",
        playback: { start: 8, end: 154 },
        cover: "./Peristeronica_RainbowMidnight_thumb.jpg",
        url: "https://youtu.be/qwLuP_dGzGM?t=8&si=pNBfkVxKQMCe9bdu",
      },
      {
        title: "ちょうだい？ ft.裏命",
        description: "デジクリ 2024前期MV企画 参加曲",
        role: "企画, 運営, 二次楽曲制作",
        date: "2024-11-07",
        type: "Music",
        aspect: "square",
        playback: { start: 5, end: 144 },
        cover: "./Peristeronica_Choudai_thumb.jpg",
        url: "https://youtu.be/nykxaC50U1s?t=5&si=zOyMJDUZ98Fymfk8",
      },
      {
        title: "BOOST GIRL ft.初音ミク",
        description: "デジクリ 2024後期MV企画 参加曲",
        role: "企画, 共同運営, 二次楽曲制作",
        date: "2025-05-22",
        type: "Music",
        aspect: "square",
        playback: { start: 4, end: 142 },
        cover: "./Peristeronica_BoostGirl_thumb.jpg",
        url: "https://youtu.be/69_7AFYwrMk?t=8&si=iCSpf0Dr_OMSmXre",
      },
      {
        title: "らぷそでぃ…？ ft.初音ミク",
        description: "デジクリ 2024後期MV企画 参加曲",
        role: "企画, 共同運営, 一次楽曲制作",
        date: "2025-05-21",
        type: "Music",
        aspect: "square",
        playback: { start: 1294, end: 1436 },
        cover: "./Peristeronica_Rhapsody_thumb.jpg",
        url: "https://youtu.be/69_7AFYwrMk?t=1299&si=bYtLpt83WL3vl8D4",
      },
      {
        title: "I F ft.裏命",
        description: "デジクリ 2025前期MV企画 参加曲",
        role: "企画, 共同運営, 二次楽曲制作",
        date: "2025-11-08",
        type: "Music",
        aspect: "square",
        playback: { start: 395, end: 540 },
        cover: "./Peristeronica_IF_thumb.jpg",
        url: "https://youtu.be/yzlxFDdrNls?t=402&si=-rHGx_6C8PJHugy7",
      },
      {
        title: "ノミナル ft.LeuR",
        description: "ボカコレ2026冬 参加曲",
        role: "企画, 作詞曲",
        date: "2026-02-23",
        type: "Music",
        cover: "./Peristeronica_Nominal_thumb.jpg",
        url: "https://www.nicovideo.jp/watch/sm45983873",
      },
    ],
    other: [
      {
        title: "1day_DTM",
        description: "短い楽曲のまとめ。",
        role: "Music",
        date: "2026-05-09",
        type: "1day_DTM",
        cover: "./Peristeronica_icon.png",
        collection: [
          {
            title: "1day_DTM archive item",
            description: "短い楽曲をここに追加します。",
            role: "Music",
            date: "2026-05-09",
            cover: "./Peristeronica_LatestWork.jpg",
          },
        ],
      },
      {
        title: "Illust",
        description: "イラストのまとめ。",
        role: "Illustration",
        date: "2026-05-09",
        type: "Illust",
        cover: "./Peristeronica_icon.png",
        collection: [
          {
            title: "Illust archive item",
            description: "イラストをここに追加します。",
            role: "Illustration",
            date: "2026-05-09",
            cover: "./Peristeronica_icon.png",
          },
        ],
      },
      {
        title: "1day_Movie",
        description: "短い映像のまとめ。",
        role: "Movie",
        date: "2026-05-09",
        type: "1day_Movie",
        cover: "./Peristeronica_icon.png",
        collection: [
          {
            title: "1day_Movie archive item",
            description: "短い映像をここに追加します。",
            role: "Movie",
            date: "2026-05-09",
            cover: "./Peristeronica_LatestWork.jpg",
          },
        ],
      },
    ],
  },
};
